Add ER diagram
vecerap/iw5-2023 pull request #1
Opened 2023-09-28 08:58 UTC by KoubaFromPucks

2023-09-28 11:44 UTC, brtkkndrl commented
So, there can be 0 "Answers" in "UserAnswer"? What would "AnswerTs" mean in that case?
![obraz](https://github.com/vecerap/iw5-2023/assets/55760594/6c446324-45a0-41b8-a4ff-6fbab730cfd4)
What's a purpouse of a line between "UserAnswer" and a "Quiz", are they not already connected through "Question" entity?
What's the point of "Order" attribute on "Answer" entity, is it order in which it is displayed? -> In that case, would it not be better random?
In assigment they mention "type" attribute on "Answer", is it included somewhere?

2023-09-28 12:30 UTC, KoubaFromPucks commented
> So, there can be 0 "Answers" in "UserAnswer"? What would "AnswerTs" mean in that case? ![obraz](https://user-images.githubusercontent.com/55760594/271268315-6c446324-45a0-41b8-a4ff-6fbab730cfd4.png) What's a purpouse of a line between "UserAnswer" and a "Quiz", are they not already connected through "Question" entity? What's the point of "Order" attribute on "Answer" entity, is it order in which it is displayed? -> In that case, would it not be better random? In assigment they mention "type" attribute on "Answer", is it included somewhere?


So, there can be 0 "Answers" in "UserAnswer"? What would "AnswerTs" mean in that case?
 0 "Answers" in "UserAnswer" means that someone skipped the question. AnswerTs means probably nothing, mazbe the time of skipping.question (for example, clicking the "Next question" button) I asked if this should be possible or not on discord server but there was no answer, so I left it at that.

What's a purpouse of a line between "UserAnswer" and a "Quiz", are they not already connected through "Question" entity?
Line between "UserAnswer" and a "Quiz", are already connected through "Question" entity, i am going to remove this relationship. Good point.

What's the point of "Order" attribute on "Answer" entity, is it order in which it is displayed? -> In that case, would it not be better random?
On discord we have discussed (https://discord.com/channels/1155553058873425980/1155553059481591851/1156289788282945576) that one of the question type could be to order the answers into the correct order. So you need to store somewhere the right order. 
![image](https://github.com/vecerap/iw5-2023/assets/80791135/dbf1fd88-344b-4512-b447-2604048d6a08)


In assigment they mention "type" attribute on "Answer", is it included somewhere?
On discord (https://discord.com/channels/461541385204400138/621774062708064268/1156162716159987783), there was a qustion what "type of question" does mean. The answer was that it could be something like "Questions with one right anser", "Question with more correct answers", ... So according to Jasek´s answer, it does not make a sense to store this information with each "Answer" entity but it would be much better to store it with "question" entity. 
![image](https://github.com/vecerap/iw5-2023/assets/80791135/6615c6a6-9317-453e-b9a7-a25538ff36a0)

2023-09-28 13:42 UTC, BRTEK007 approved these changes

2023-09-28 17:14 UTC, vecerap commented on docs/ERD.pdf
What does the Ts suffix mean in `AnswerTs`, etc?

According to the assignment, the score metrics during quiz for each user is missing. There should be connection between `User` and `Quiz` with attribute score and date maybe (this is an extra information to differentiate possible duplicit scores - in UI this could be shown in table with dates, scores for each individual quiz for every user). What do you say about this addition @BRTEK007 ?

2023-09-28 18:58 UTC, BRTEK007 commented on docs/ERD.pdf
I would add it, but without the date, keeping only the best score on a given `Quiz`.

2023-09-28 22:23 UTC, vecerap commented on docs/ERD.pdf
@BRTEK007 I agree with this suggestion, this seems to be easier to implement. What do you think @KoubaFromPucks ?

2023-09-29 04:51 UTC, KoubaFromPucks commented on docs/ERD.pdf
Ts means time stamp. I wrote this to make it clear that time is involved. 

The realtioship between User and Quiz that determinates score is not really necessery. You can always calculate Score when you need it. But you are all right that this realtionship can make our work easier. But now i am confused, if i should add new realtionship betwwen Quiz and User or just add best score attribute at given Quiz. @BRTEK007 @vecerap

2023-09-29 08:49 UTC, vecerap commented on docs/ERD.pdf
I am not aware how this information will be calculated.

If you add attribute to Quiz entity, you will store only the best score among all users on a given quiz, whereas if you store it in binding entity, you would store the best score for each user on a given quiz. This should be also resolved amog us @BRTEK007

2023-09-29 08:53 UTC, KoubaFromPucks commented on docs/ERD.pdf
OK, now i understand and i agree.

2023-09-29 10:31 UTC, vecerap approved these changes

2023-09-29 10:36 UTC, vecerap requested changes
Squash your commits into single commit with meanigfull message

2023-09-30 19:03 UTC, vecerap approved these changes

2023-09-30 19:05 UTC, merged