Repair and add search tests
vecerap/iw5-2023 pull request #38
Opened 2023-11-16 14:06 UTC by KoubaFromPucks

New tests were added for search functions and the ones that already existed, were changed. Now all words of search text has to be present in text where you are searchnig. Tests expect that the search **IS NOT CASE SENSITIVE**.

2023-11-16 15:53 UTC, vecerap commented on src/Quizzer.API.BL.UnitTests/QuestionFacadeTest.cs
> +                GetQuestionEntityWith("sth totally different", "38222E2E-A9AF-414E-BEA1-C82FF948E9CD")
Cannot be this rewritten in a way that this test case parsing can be parsed using inline data attribute?

2023-11-16 16:22 UTC, KoubaFromPucks commented on src/Quizzer.API.BL.UnitTests/QuestionFacadeTest.cs
> +                GetQuestionEntityWith("sth totally different", "38222E2E-A9AF-414E-BEA1-C82FF948E9CD")
It can be rewriten. I was actually thinking about it but i decided to do it this way because it seemed to me little wired that repository (Mock) will always return to you just one record and than proccess this one entity. But in fact (with [InlineData]) the code would be simplier and cleaner i guess. If you think that it is better to use `[Theory]` with [`InlineData`] instead of `[Fact]` it should not be a problem.

2023-11-18 11:50 UTC, vecerap commented on src/Quizzer.API.BL.UnitTests/QuestionFacadeTest.cs
> +                GetQuestionEntityWith("sth totally different", "38222E2E-A9AF-414E-BEA1-C82FF948E9CD")
I would suggest to use `InlineData` as this could be potentially considered a bad practice during evaluation.

2023-11-19 16:12 UTC, KoubaFromPucks commented on src/Quizzer.API.BL.UnitTests/QuestionFacadeTest.cs
> +                GetQuestionEntityWith("sth totally different", "38222E2E-A9AF-414E-BEA1-C82FF948E9CD")
Done

2023-11-19 17:25 UTC, vecerap requested changes
Squash commits

2023-11-19 17:46 UTC, KoubaFromPucks commented
> Squash commits

Done

2023-11-20 08:22 UTC, vecerap approved these changes

2023-11-25 19:50 UTC, brtkkndrl approved these changes

2023-11-25 20:00 UTC, merged