Created quiz playing page
vecerap/iw5-2023 pull request #66
Opened 2024-01-23 17:13 UTC by KoubaFromPucks

A quiz playing page was created and some changes had to be done too.

In Question Facade there was repared function to handle multiAnswer question. BEFORE: userAnswer.AnswerScore += answerEntity!.IsCorrect == false ? 1 : -0.5; AFTER" userAnswer.AnswerScore += answerEntity!.IsCorrect? -1 : 0.5;

If there were for example 3 answers where 2 are correct and someone would select all answers he should get 1.5 points (+2 for checking good answers and -0.5 for bad answer). When he uncheck all answers, then he should have 0 points. But because of previous code, he would have 1.5 points (-1 for uncheck good answers, +1 for uncheck bad answer). Now he will have 0 points because (-2 for uncheck good answers, +0.5 for uncheck bad answer).

Second change is removing this:
userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0); If there were for example 3 answers where 2 are correct and someone would select just the bad answer, then he would have 0 points. If he checked then the correct answers, he would have 2 points. But if someone would check all answers in same time, then he would have 1.5 points with same checked answers.

In handling order Choice "userAnswer.SelectedAnswers.Remove(answer);" was added because answer was deleted from database but not from collection so when some answer was deleted then when counting points, the answer was still counted as answered. If the answer was correct, but user wanted to delete order, then the point for this answer was counted.

Other changes are there because this scenario:
when user filled orders of 2/3 answers (A = not filled, B = 2, C = 3) (correct are A = 1, B = 2, C = 3) the algorithm would give user just one point instead of 2 points. Because in cycle there would be compared firstly order of A and B (0 points),  then B and C (0 points) and then C and C (1 point).

2024-01-23 17:54 UTC, brtkkndrl reviewed
When doing "Great Britan" quiz as "John Ronald Reuel Tolkien" I get an errror:
`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'hideById' ('hideById' was undefined).`

2024-01-23 18:06 UTC, brtkkndrl requested changes
I would limit size of answer image.

2024-01-23 18:21 UTC, KoubaFromPucks commented
> When doing "Great Britan" quiz as "John Ronald Reuel Tolkien" I get an errror: `crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not find 'hideById' ('hideById' was undefined).`

It works fine to me. Try to look to sources if you have latest version of js file, like on this picture.
![image](https://github.com/vecerap/iw5-2023/assets/80791135/77cb8ca2-a1de-4cbb-af69-492826bc3d33)

if it is not the latest version, try to use location.reload()  on console, check again and if it does not work, you need to find a way yourself... 
![image](https://github.com/vecerap/iw5-2023/assets/80791135/0d981320-164a-47a5-8ad1-7ae142bbf31d)

2024-01-23 18:54 UTC, KoubaFromPucks commented
> I would limit size of answer image.

Done

2024-01-23 19:56 UTC, vecerap commented
> > When doing "Great Britan" quiz as "John Ronald Reuel Tolkien" I get an errror: `crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not find 'hideById' ('hideById' was undefined).`
> 
> It works fine to me. Try to look to sources if you have latest version of js file, like on this picture. ![image](https://private-user-images.githubusercontent.com/80791135/299058336-77cb8ca2-a1de-4cbb-af69-492826bc3d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzk5NjksIm5iZiI6MTcwNjAzOTY2OSwicGF0aCI6Ii84MDc5MTEzNS8yOTkwNTgzMzYtNzdjYjhjYTItYTFkZS00Y2JiLWFmNjktNDkyODI2YmMzZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE5NTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzUzMTI5NDU1YmE5Mzc2YTMzNzBjYzU1ZTgxMmRmZTc1YjM5N2ZkNjBhYWQyNTZlOTc5MjRlMmQwYzJlMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1o8KIbz29BMfQMxyAM0QpBEqzgKJSivtNDg9EOXlf_E)
> 
> if it is not the latest version, try to use location.reload() on console, check again and if it does not work, you need to find a way yourself... ![image](https://private-user-images.githubusercontent.com/80791135/299058672-0d981320-164a-47a5-8ad1-7ae142bbf31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzk5NjksIm5iZiI6MTcwNjAzOTY2OSwicGF0aCI6Ii84MDc5MTEzNS8yOTkwNTg2NzItMGQ5ODEzMjAtMTY0YS00N2E1LThhZDEtN2FlMTQyYmJmMzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE5NTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDBiODYxMGU1NzdiMmQwNTIwMjIyNDVmMDE3NTk4NDk4OWI2Mjc1YzIwNjc0OGQ0YWRkNGE1NGZkNjIyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fOeZZlR4Qj2bxjA2zX0hTswd2BA0S4x8mM2gyuTQy8Q)

You probably have cached these JS codes, mine has same errors.

2024-01-23 19:58 UTC, vecerap commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> -            userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0);
What if the user selects only bad answers but never corrects them? Wouldn't the score be negative?

2024-01-23 19:58 UTC, vecerap commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> +                userAnswer.SelectedAnswers.Remove(answer);
Shouldn't this change be performed through selected answer repository?

2024-01-23 19:58 UTC, vecerap commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> +                    .SingleOrDefault(a => a.Order == correctAnswer.Order, null)?.AnswerId ?? Guid.Empty;
My algorithm works with defined orders. If some answer was omitted from order, then it should not be included in the user answers. So the possible fix is only filter user answers without defined order and leave only answers with order. Hit me up on discord about this change.

2024-01-23 19:58 UTC, vecerap commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor.cs
> +        await JsRuntime.InvokeVoidAsync("import", "/js/general.js", false);
Shouldn't you save module reference in `JSObjectReference `instance? This is probably reason why it does not work on our instances.

![image](https://github.com/vecerap/iw5-2023/assets/93704213/1cdf3840-9995-450d-853f-f13b4cf397bc)


[See the example here](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-8.0#javascript-isolation-in-javascript-modules)

2024-01-23 20:22 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> -            userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0);
Yes, it would be. But if you want to keep this in incremental mode as you did it, there is no other way. If we want to set minimum to 0, then the score of answer has to be counted like orderChoice question - start from zero and iterate through all answered questions.

2024-01-23 20:23 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> +                userAnswer.SelectedAnswers.Remove(answer);
It should but it does not. And i could find how to do that. Some hint?

2024-01-23 20:44 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> -            userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0);
So i will do it as it is in order, based on our call.

2024-01-23 20:52 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> +                    .SingleOrDefault(a => a.Order == correctAnswer.Order, null)?.AnswerId ?? Guid.Empty;
In call we agreed that this way is ok

2024-01-23 21:04 UTC, brtkkndrl commented
> > When doing "Great Britan" quiz as "John Ronald Reuel Tolkien" I get an errror: `crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not find 'hideById' ('hideById' was undefined).`
> 
> It works fine to me. Try to look to sources if you have latest version of js file, like on this picture. ![image](https://private-user-images.githubusercontent.com/80791135/299058336-77cb8ca2-a1de-4cbb-af69-492826bc3d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDM3OTMsIm5iZiI6MTcwNjA0MzQ5MywicGF0aCI6Ii84MDc5MTEzNS8yOTkwNTgzMzYtNzdjYjhjYTItYTFkZS00Y2JiLWFmNjktNDkyODI2YmMzZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwNTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NjZkMjFkMjU3MTEzYWY0NDRlNTBiYWM2ZWIwYWIzOWYyYWZlMmQ3MDBjYmFiNzg5ZTE5MmFjMjcwMmVhOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tUt61BQy2aYDvi0RApYv19rcoZ1t4CO-yGh6eSzUyw8)
> 
> if it is not the latest version, try to use location.reload() on console, check again and if it does not work, you need to find a way yourself... ![image](https://private-user-images.githubusercontent.com/80791135/299058672-0d981320-164a-47a5-8ad1-7ae142bbf31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDM3OTMsIm5iZiI6MTcwNjA0MzQ5MywicGF0aCI6Ii84MDc5MTEzNS8yOTkwNTg2NzItMGQ5ODEzMjAtMTY0YS00N2E1LThhZDEtN2FlMTQyYmJmMzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwNTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOGM1ZmFjNDY3ZjM5OGE2Y2JhY2NkZDJkODZhMzgxMDYzMjlmMTlmNjc2MWMyMzIyZjZjMTk2NTNhYzFhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zI9zq__jLspSj5cEQVsevHahDvxeYK06-UuEGvRhgnc)

I had it cached, works now.

2024-01-23 21:11 UTC, brtkkndrl approved these changes

2024-01-23 21:20 UTC, vecerap commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> -            userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0);
Ok, as we agreed, change the score counting as iterating through all answers.

2024-01-24 14:58 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuestionFacade.cs
> -            userAnswer.AnswerScore = Math.Max(userAnswer.AnswerScore, 0);
Done

2024-01-24 14:59 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor.cs
> +        await JsRuntime.InvokeVoidAsync("import", "/js/general.js", false);
Done

2024-01-25 19:57 UTC, vecerap commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor
> +}
I would put here an else branch with some placeholder text something like "Loading data..."

I read somewhere in MS docs that this prevents DOM being spilled out during the data loading.

2024-01-25 19:57 UTC, vecerap commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor.cs
> +            await _generalJsModule.InvokeVoidAsync("showMessageBox",
Is message box function some sort of global function in entire JS on browser, or is it something module specific? Isn't it better to call it from IJS runtime? What if the general module is not loaded either?

2024-01-25 19:57 UTC, vecerap commented on src/Quizzer.Web.App/wwwroot/js/general.js
>      document.getElementById("msgBox").classList.add(success ? "alert-success" : "alert-danger");
I think this is doable in Blazor too. Just have two message box elements in some sort of if statement:

```
if(showSuccess) <div class success>

if(showError) <div class error>
```

[Or other approach](https://stackoverflow.com/questions/63693734/how-to-show-hide-an-element-in-real-time-blazor)

Doing that will avoid relying on proper JS import when handling errors. Error display should be made as fail-safe as possible.

2024-01-26 15:14 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor
> +}
Done

2024-01-26 15:16 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/Quiz/QuizPlayingPage.razor.cs
> +            await _generalJsModule.InvokeVoidAsync("showMessageBox",
I found that this can not happen because `await JsRuntime.InvokeAsync<IJSObjectReference>("import", "./js/general.js");` will never return null, so those lines of code are removed now.

2024-01-26 15:18 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/wwwroot/js/general.js
>      document.getElementById("msgBox").classList.add(success ? "alert-success" : "alert-danger");
Ok, i completly changed this including yours and @BRTEK007 pages. Now there cant be a problem with JS because they are not used anymore for messageboxes. Now there are 2 functions in `PageBase.cs` that will show and hide messagebox

2024-01-27 17:16 UTC, vecerap approved these changes

2024-01-27 17:17 UTC, merged