Missing stuff from first deadline
vecerap/iw5-2023 pull request #67
Opened 2024-01-25 16:55 UTC by brtkkndrl

What changed:
- styling
- ability to go to detail from search
- question list page
- answer list page
- creating and deleting users + migration to cascade user answers when deleting
- creating and deleting quizzes
- creating and deleting questions and answers

What could be discussed:
- unified alerts of error and confirmation boxes before deleting across all pages
- creating questions and answers from list page (is in assignment) however in our case problematic since question is binded to quiz
- making quizz views more explicit (don't show PLAY, EDIT, VIEW RESULT buttons if those actions can't be performed)
- refactoring navigation, maybe NavigationManager > <a href="">
- connecting with quiz playing PR

2024-01-25 20:19 UTC, vecerap requested changes
The creation forms lacks cancel buttons which will redirect user back to the previous page or the base page of the creation form

I am not sure about for loop how they behave when the collection which they iterate is null.

Also use concise style with explicit files with code behind rather than enclosing code in `@code` blocks

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Components/AnswerListCard.razor
> +				}
Would add else branch with placeholder text similar used in `alt` tag

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +            </div>*@
This should be later removed to avoid points loss

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +}
How does the foreach behave if Answers is null?

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/AnswerList.razor
> +@inject IJSRuntime JsRuntime
This should be at the top of file

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/AnswerList.razor
> +}
What if the answers are null, would not this throw exception on null value?

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuestionList.razor
> +@inject IJSRuntime JsRuntime
This should be at the top of the file

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuestionList.razor
> +}
The same as before, null handling

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuizEdit.razor
>  @inject IJSRuntime JsRuntime
Move to top

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuizEdit.razor
> +        @foreach (var question in Quiz.Questions)
Nullability check maybe

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +        //}
Should be later removed

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +                await QuizFacade.UpdateAsync(Quiz);//TODO get http response with error code
What about this todo?

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/UserEdit.razor
> +}
Maybe some placeholder in else branch before it is loaded properly

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/Pages/UserList.razor
>  }
Nullability during users loading

2024-01-25 20:19 UTC, vecerap commented on src/Quizzer.Web.App/wwwroot/js/general.js
> +    alert(text);
cannot IJS runtime invoke alert function directly?

2024-01-25 20:24 UTC, vecerap commented
> unified alerts of error and confirmation boxes before deleting across all pages

Does JS offer yes/no popup box?

> creating questions and answers from list page (is in assignment) however in our case problematic since question is binded to quiz

I could reach Pluskal via email about that.

> making quizz views more explicit (don't show PLAY, EDIT, VIEW RESULT buttons if those actions can't be performed)

On buttons could be applied "disabled" state via bootstrap if I am not mistaken

> refactoring navigation, maybe NavigationManager >

Could you elaborate?

> connecting with quiz playing PR

Yes this will be resolved once the work is merged.

2024-01-25 22:48 UTC, brtkkndrl commented
> The creation forms lacks cancel buttons which will redirect user back to the previous page or the base page of the creation form
> 
> I am not sure about for loop how they behave when the collection which they iterate is null.
> 
> Also use concise style with explicit files with code behind rather than enclosing code in `@code` blocks

Back button in browser does that.
Collections could be set to empty collection as initial value so they would never be null.
How is it more concise when you have to declare an extra class and use extra file?

2024-01-25 22:58 UTC, brtkkndrl commented
> > unified alerts of error and confirmation boxes before deleting across all pages
> 
> Does JS offer yes/no popup box?
> 
> > making quizz views more explicit (don't show PLAY, EDIT, VIEW RESULT buttons if those actions can't be performed)
> 
> On buttons could be applied "disabled" state via bootstrap if I am not mistaken
> 
> > refactoring navigation, maybe NavigationManager >
> 
> Could you elaborate?

There is a confirmation popup in js, we could use it.

The problem is in how to get this logic to frontend, Those checks for playability/editability are performed in the API, ideally we would return this in a model.

Putting string URLs in html link tags, seems not optimal, I was wondering if there is not a better way to do this, and have urls defined in one place.

2024-01-26 15:34 UTC, KoubaFromPucks commented on src/Quizzer.API.DAL/Migrations/20240123223452_SelectedAnswersCascade.cs
This migration is completly useless right? I guess that if not, there would be some code...

2024-01-26 15:34 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +            Quiz = await QuizFacade.GetByIdAsync(Id);//TODO error handling
Maybe better to have no todos in PR, i guess

2024-01-26 22:04 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/AnswerList.razor
> +@inject IJSRuntime JsRuntime
moved

2024-01-26 22:05 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuestionList.razor
> +@inject IJSRuntime JsRuntime
moved

2024-01-26 22:06 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor
>  @inject IJSRuntime JsRuntime
moved

2024-01-26 22:08 UTC, brtkkndrl commented on src/Quizzer.Web.App/wwwroot/js/general.js
> +    alert(text);
it can, fixed

2024-01-26 22:12 UTC, brtkkndrl commented on src/Quizzer.API.DAL/Migrations/20240123223452_SelectedAnswersCascade.cs
removed

2024-01-26 22:14 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/AnswerListCard.razor
> +				}
done

2024-01-26 22:16 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +}
added check

2024-01-26 22:19 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/AnswerList.razor
> +}
added check

2024-01-26 22:20 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuestionList.razor
> +}
added check

2024-01-26 22:21 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor
> +        @foreach (var question in Quiz.Questions)
added check

2024-01-26 22:22 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/UserEdit.razor
> +}
added

2024-01-26 22:24 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/UserList.razor
>  }
added

2024-01-26 22:36 UTC, brtkkndrl commented
Confirmation popups for removal of user, quiz, question added.
null checks added

Question detail page has code for when you could create question there, + answer removal should not be working-> needs refactoring, waiting on information from if we need question creation from list page.

2024-01-27 17:25 UTC, vecerap commented
@BRTEK007 You have conflicts on PR

2024-01-29 07:48 UTC, KoubaFromPucks requested changes

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Components/AnswerEditForm.razor.cs
>          }
So if there will be some error during saving, user will not be notified?

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +            </div>*@
What about those comments?

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +}*@
What about those comments?

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/QuestionDetailPage.razor.cs
> +    //}
Commented code..

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/QuestionDetailPage.razor.cs
> +                await OnDelete.InvokeAsync(null);
Why null argument?

2024-01-29 07:48 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +    //}
Too much commented code

2024-01-29 16:46 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +            </div>*@
gone

2024-01-29 16:49 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +        //}
gone

2024-01-29 16:49 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +                await QuizFacade.UpdateAsync(Quiz);//TODO get http response with error code
gone

2024-01-29 16:49 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +            Quiz = await QuizFacade.GetByIdAsync(Id);//TODO error handling
gone

2024-01-29 16:50 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/AnswerEditForm.razor.cs
>          }
error handling was moved to AnswerDetail page

2024-01-29 16:51 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +            </div>*@
gone

2024-01-29 16:51 UTC, brtkkndrl commented on src/Quizzer.Web.App/Components/QuestionEditForm.razor
> +}*@
gone

2024-01-29 16:51 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuestionDetailPage.razor.cs
> +    //}
gone

2024-01-29 16:52 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuestionDetailPage.razor.cs
> +                await OnDelete.InvokeAsync(null);
gone

2024-01-29 16:53 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizEdit.razor.cs
> +    //}
gone

2024-01-30 12:08 UTC, vecerap commented
> How is it more concise when you have to declare an extra class and use extra file?

@BRTEK007 For extra small razor coponents I would not mind that, that was a suggestion

2024-01-30 12:12 UTC, vecerap approved these changes

2024-01-30 12:13 UTC, vecerap commented
@BRTEK007 After approvals, squash commits

2024-01-30 14:01 UTC, KoubaFromPucks approved these changes

2024-01-30 19:02 UTC, merged