Quiz logic edit
vecerap/iw5-2023 pull request #68
Opened 2024-01-29 19:31 UTC by KoubaFromPucks

Updated Quiz list page and related thing
Now QuizDetail model has 3 new bool attributes: 
`IsPlayable` - Specific for user, tells if user can play this quiz (quiz is running and that user did not filled it)
`CanSeeResults`  - Specific for user, tells if user can see his results (That user filled it)
`IsEditable` - Tells if quiz can be edited (quiz is runnig and noone filled it)

To obtain those things it was necessary to create new functions in quiz facade who will evaluate those attributes, but because there is not need to get all quizes for specific user every time , there was created new method in Quiz facade that does those things. So, compared to method GetAll, the new method GetAllForUser, additionally fills attributes `IsPlayable` and `IsEditable`.  

Because of this new method in API facade it was necessary to create new method in API Quiz controller, regenerate API clients and add support for this in client facade. 

Becuase of new attributes in detail model, also there is change in it's Mapper profile where those attributes have to be ignored during mapping because those attributes are filled additionaly.

I have also created a modal window. Because as @BRTEK007 wanted, user can view quiz, question and answer details even when quiz is running, so before he sees details, he will be asked if he really want to see detail. Component should be easy to reuse for another things. 

In QuizListPage are now disabled buttons which are not possible to click on - if user already filled quiz, he is not able to do it again, and if he did not, he cant see his results.

2024-01-29 21:44 UTC, brtkkndrl commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
> +        IRepository<CompletedQuizEntity> completedQuizRepository = uow.GetRepository<CompletedQuizEntity>();
this could be after the quizEntity null check

2024-01-29 21:44 UTC, brtkkndrl commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
> +        bool wasCompletedByUser = completedQuizRepository
Isn't this the same check from CanUserSeeResults? maybe it can be put into a function.

2024-01-29 22:00 UTC, brtkkndrl commented
Quiz detail page still needs to be accesible even when not editable (from search for example). Could be done by adding note on top of quizEditPage and disabling all inputs and buttons. In the quiz list view  detail button text could change "View"/"Edit".

2024-01-29 22:02 UTC, brtkkndrl requested changes

2024-01-29 22:02 UTC, brtkkndrl commented on src/Quizzer.Web.App/Pages/QuizListPage.razor
> +                        @if (model.IsEditable)
instead of hiding these buttons I would disable them

2024-01-30 09:19 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
> +        IRepository<CompletedQuizEntity> completedQuizRepository = uow.GetRepository<CompletedQuizEntity>();
Just line 54 can be placed after null check... Done

2024-01-30 09:19 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
> +        bool wasCompletedByUser = completedQuizRepository
Yeah, good idea... Done

2024-01-30 09:19 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Pages/QuizListPage.razor
> +                        @if (model.IsEditable)
Done... except Edit button - according to your comment, there is just change between "Edit" and "View detail"

2024-01-30 12:04 UTC, vecerap commented
@KoubaFromPucks Could you describe what you did on PR?

2024-01-30 12:33 UTC, KoubaFromPucks commented
> @KoubaFromPucks Could you describe what you did on PR?

done

2024-01-31 15:27 UTC, vecerap commented on src/Quizzer.API.BL/ApiBLInstaller.cs
> +        services.AddScoped<IQuizChecker, QuizFacade>();
When I though about this initialization I realized, that it is not necessary, because line above is init with interfaces which will init this correctly. You can try this on your machine but on mine it works when I remove this line.

2024-01-31 15:27 UTC, vecerap commented on src/Quizzer.API.BL/Facades/AnswerFacade.cs
> +    }
You could have used joins on answers instead of this database call, and just pass quiz directly from answer.question.quiz, this would simplify the code

2024-01-31 15:27 UTC, vecerap commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
>              throw new ArgumentException("Start time is later than end time");
Using indentation only on statements is not consistent with the rest of the codebase, they could have complaints on this

Either have the statement on one line or use brackets.

2024-01-31 15:27 UTC, vecerap commented on src/Quizzer.Web.App/Components/ModalWindow.razor
What is this modal window?

2024-01-31 16:28 UTC, KoubaFromPucks commented on src/Quizzer.Web.App/Components/ModalWindow.razor
When you want to see detail of quiz from question list and you did not played the quiz then the modal window is showed. 
![image](https://github.com/vecerap/iw5-2023/assets/80791135/55c46ffe-e0ed-4367-85c8-204617965250)

2024-01-31 16:28 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/QuizFacade.cs
>              throw new ArgumentException("Start time is later than end time");
Ok, i ran all if statements through regex and repared all if and else statements

2024-01-31 16:28 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/Facades/AnswerFacade.cs
> +    }
Yes, but problem is, that If you get question by id, in AnswerFacade there is not defined `IncludesNavigationPathDetails` and i do not know if i should define it, maybe some code would look now stupid and it could possibly load to much data in many cases. And if i would use method `GetListByPredicate` then i am not sure if the code would be simplified.

2024-01-31 16:28 UTC, KoubaFromPucks commented on src/Quizzer.API.BL/ApiBLInstaller.cs
> +        services.AddScoped<IQuizChecker, QuizFacade>();
Yes it works without the line, so i have deleted it

2024-01-31 17:10 UTC, brtkkndrl requested changes
Images in quiz result page could be made smaller similar to quiz playing page.
In QuesitonList.razor.cs and AnswerList.razer.cs you could filter uneditable quizzes/question after loading from API.

2024-01-31 17:33 UTC, KoubaFromPucks commented
> Images in quiz result page could be made smaller similar to quiz playing page. In QuesitonList.razor.cs and AnswerList.razer.cs you could filter uneditable quizzes/question after loading from API.

Done

2024-01-31 19:13 UTC, brtkkndrl approved these changes

2024-01-31 20:48 UTC, vecerap approved these changes

2024-01-31 20:49 UTC, vecerap commented on src/Quizzer.API.BL/Facades/AnswerFacade.cs
> +    }
Ok then leave it as it is

2024-01-31 20:54 UTC, merged